### ISSUE TITLE
Nested files

### ISSUE THREAD

**Issue by reaganlo** [RafikFarhad/clang-format-github-action#2]
@RafikFarhad Is there a way to specify all the nested .cpp and .hpp files in the repo as part of **sources input** ?

**Comment by RafikFarhad** [comment]
Hi @reaganlo, 
I did not know much about nested .cpp or .hpp files but if you are trying to format all the .cpp and .hpp files in a repo you can do this: `sources: "./**/*.(hpp|cpp)"`

**Comment by reaganlo** [comment]
@RafikFarhad Thanks for the prompt response. 
E.g. 
```
       repo-dir:
                   - file1.hpp 
                   - file2.cpp
                   - file3.cpp
                   - readme
                   - dir1:
                          - file4.hpp
                          - file5.cpp
                          - file6.py
                          - file7.config
                   - dir2:
                          - readme
                          - file8.cpp
```
 
I am looking for a regex where clang-format would just parse **file1.hpp, file2.cpp, file3.cpp, file4.hpp, file5.cpp and file8.cpp**
If I run it locally, I would do this:
**find . -regex '.*\.\(cpp\|hpp\)' -exec clang-format -style=file -i {} \;**

Any suggestions?
